version: "1.0"

services:
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      command: certonly --webroot -w /var/www/certbot --force-renewal --email mcdanije22@gmail.com -d mysetupshare.com --agree-tos
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
