version: "3.9"

services:
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: ./server/.env
    ports:
      - 5000:5000
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: ./client/.env.local
    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
    env_file: .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./Nginx
    ports:
      - 80:80
      - 443:443
volumes:
  database-data:
