version: "1.0"

volumes:
  database-data:
services:
  database:
    image: "postgres:14"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: share_station
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - database-data:/var/lib/postgresql/12/main/
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./Nginx
    ports:
      - 80:80
      - 443:443
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  server:
    depends_on:
      - postgres
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
