version: "1.0"

services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: ./client/.env.local
    ports:
      - 3000:3000
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    depends_on:
      - postgresql_database
    environment:
      NODE_ENV: production
    env_file: ./server/.env
    ports:
      - 5000:5000
  postgresql_database:
    container_name: postgresql_database
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=share_station
    env_file: .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./Nginx
    ports:
      - 80:80
      - 443:443
volumes:
  database-data:
